### ISSUE TITLE
Problems with Syntax in OS X with wireshark 2.6.0

### ISSUE THREAD

**Issue by masonke** [strizhechenko/tshark-tcp-stream-splitter#7]
OS X 10.12.6
TShark (Wireshark) 2.6.0
zsh and bash tried

Having problems with the syntax and could use some help.

The trace file name is part1a.pcap and is located in ~/Downloads. I am running the command in the Downloads directory. However, I cannot seem to get the syntax correct. Various combinations of the path parameter have been tried, but I keep getting a path error:
```
$ tshark -X lua_script:tcp-stream-splitter.lua -X lua_script1:/Users/bofh/Downloads/ -n -r ./part1a.pcap 
tshark: Lua: Error during loading:
 [string "/Users/bofh/.local/lib/wireshark/plugins/t..."]:4: You should pass -X lua_script1:$PATH_TO_SOURCE_PCAP_FILE

```
For the path, I have tried:
```
-X lua_script1:/Users/bofh/Downloads
-X lua_script1:/Users/bofh/Downloads/
-X lua_script1:/Users/bofh/Downloads/part1a.pcap
-X lua_script1:~/Downloads
-X lua_script1:.
```
But without success. Could someone tell me what I am doing wrong here?
Thanks!

**Comment by strizhechenko** [comment]
Hi!

```
[string "/Users/bofh/.local/lib/wireshark/plugins/t..."]
```

I don't know if this script works while been put to this directory. Can you try to pass full path to it in `lua_script:`?

I re-tested it (with 2.4.2 and 2.6.1):

```
mkdir -p 1.pcap.parts
tshark -X lua_script:/Users/oleg/tcp-stream-splitter.lua -X lua_script1:1.pcap -n -r 1.pcap
```

This way everything work fine.

**Comment by masonke** [comment]
That worked, thank you. 
The script only outputs streams that have a syn in them. That would be from the statement "local SYN = 2", correct?

When running, is it expected to see the packets spool on the screen?

Thank you very much for a great utility!

**Comment by strizhechenko** [comment]
> The script only outputs streams that have a syn in them.

Yes, I had to save only "full" connections to analyze them.

`local SYN = 2` is probably unused.

If you need to get connections without SYN packet you probably need to look at:

```
corrupted = not (syn == 1),
```

> When running, is it expected to see the packets spool on the screen?

It was for debugging purpose, but I don't know how to suppress this output.

**Comment by masonke** [comment]
Thanks for the information. It is amazing just how fast this utility is vs running tshark over and over in a script.

I will look at the code and see if there is a way to disable the scrolling packets, but as long as they are expected, it is not a problem.

Thanks!
